Repository bsoyka/gravify, pull requests merged in 2019-09, with the labels that each got.

#8 Add unit tests
  setup.py
  tests/test_main.py
Labels: enhancement

#9 Create code of conduct
  CODE_OF_CONDUCT.md
Labels: documentation, enhancement

#10 Make a basic README file
  README.md
  docs/logo.png
  docs/logo.xcf
Labels: documentation
